// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ChapterDocumentDataSlicesSlice = never;

/**
 * Content for Chapter documents
 */
interface ChapterDocumentData {
  /**
   * Chapter field in *Chapter*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Please enter your chapter number here
   * - **API ID Path**: chapter.chapter_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  chapter_number: prismic.NumberField;

  /**
   * Chapter Name field in *Chapter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please enter your chapter name here
   * - **API ID Path**: chapter.chapter_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  chapter_name: prismic.KeyTextField;

  /**
   * Story field in *Chapter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please enter your story name here
   * - **API ID Path**: chapter.story_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  story_name: prismic.KeyTextField;

  /**
   * Content field in *Chapter*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Please enter your chapter content here
   * - **API ID Path**: chapter.chapter_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  chapter_content: prismic.RichTextField;

  /**
   * Chapter Colour field in *Chapter*
   *
   * - **Field Type**: Color
   * - **Placeholder**: Please enter your chapter colour here
   * - **API ID Path**: chapter.chapter_colour
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  chapter_colour: prismic.ColorField;

  /**
   * Slice Zone field in *Chapter*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: chapter.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ChapterDocumentDataSlicesSlice> /**
   * Meta Title field in *Chapter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: chapter.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Chapter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: chapter.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Chapter*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: chapter.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Chapter document from Prismic
 *
 * - **API ID**: `chapter`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ChapterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ChapterDocumentData>,
    "chapter",
    Lang
  >;

type DoodleDocumentDataSlicesSlice = never;

/**
 * Content for Doodle documents
 */
interface DoodleDocumentData {
  /**
   * Title field in *Doodle*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Doodle title goes here
   * - **API ID Path**: doodle.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Date field in *Doodle*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Date goes here
   * - **API ID Path**: doodle.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Timestamp field in *Doodle*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: Timestamp goes here
   * - **API ID Path**: doodle.timestamp
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  timestamp: prismic.TimestampField;

  /**
   * Author field in *Doodle*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Author name goes here
   * - **API ID Path**: doodle.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  author: prismic.RichTextField;

  /**
   * Description field in *Doodle*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description goes here
   * - **API ID Path**: doodle.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Notes field in *Doodle*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Notes can go here
   * - **API ID Path**: doodle.notes
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  notes: prismic.RichTextField;

  /**
   * Picture field in *Doodle*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: doodle.picture
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Doodle*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: doodle.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DoodleDocumentDataSlicesSlice> /**
   * Meta Title field in *Doodle*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: doodle.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Doodle*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: doodle.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Doodle*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: doodle.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Doodle document from Prismic
 *
 * - **API ID**: `doodle`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DoodleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<DoodleDocumentData>, "doodle", Lang>;

type HumanArticleDocumentDataSlicesSlice = never;

/**
 * Content for Human Article documents
 */
interface HumanArticleDocumentData {
  /**
   * Title field in *Human Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Placeholder title
   * - **API ID Path**: humanArticle.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Date field in *Human Article*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Placeholder date
   * - **API ID Path**: humanArticle.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Author field in *Human Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Placeholder author
   * - **API ID Path**: humanArticle.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Description field in *Human Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Placeholder description
   * - **API ID Path**: humanArticle.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Human Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: humanArticle.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Article Content field in *Human Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Article content goes here
   * - **API ID Path**: humanArticle.article_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  article_content: prismic.RichTextField;

  /**
   * Slice Zone field in *Human Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: humanArticle.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HumanArticleDocumentDataSlicesSlice> /**
   * Meta Title field in *Human Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: humanArticle.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Human Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: humanArticle.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Human Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: humanArticle.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Human Article document from Prismic
 *
 * - **API ID**: `humanArticle`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HumanArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HumanArticleDocumentData>,
    "humanArticle",
    Lang
  >;

type LabsArticleDocumentDataSlicesSlice = never;

/**
 * Content for Labs Article documents
 */
interface LabsArticleDocumentData {
  /**
   * Title field in *Labs Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Placeholder title
   * - **API ID Path**: labsArticle.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Timestamp field in *Labs Article*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: Placeholder timestamp
   * - **API ID Path**: labsArticle.timestamp
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  timestamp: prismic.TimestampField;

  /**
   * Author field in *Labs Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Author name goes here
   * - **API ID Path**: labsArticle.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  author: prismic.RichTextField;

  /**
   * Description field in *Labs Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Placeholder description
   * - **API ID Path**: labsArticle.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Labs Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: labsArticle.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Article Content field in *Labs Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Article content goes here
   * - **API ID Path**: labsArticle.article_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  article_content: prismic.RichTextField;

  /**
   * Slice Zone field in *Labs Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: labsArticle.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LabsArticleDocumentDataSlicesSlice> /**
   * Meta Title field in *Labs Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: labsArticle.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Labs Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: labsArticle.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Labs Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: labsArticle.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Labs Article document from Prismic
 *
 * - **API ID**: `labsArticle`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LabsArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LabsArticleDocumentData>,
    "labsArticle",
    Lang
  >;

type PostDocumentDataSlicesSlice = never;

/**
 * Content for Post documents
 */
interface PostDocumentData {
  /**
   * Title field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Placeholder title
   * - **API ID Path**: post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Date field in *Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: post.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Author field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Author name goes here
   * - **API ID Path**: post.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Description field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Placeholder description
   * - **API ID Path**: post.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Image field in *Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Post Content field in *Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Placeholder post content goes here
   * - **API ID Path**: post.post_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  post_content: prismic.RichTextField;

  /**
   * Slice Zone field in *Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PostDocumentDataSlicesSlice> /**
   * Meta Title field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Post document from Prismic
 *
 * - **API ID**: `post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PostDocumentData>, "post", Lang>;

type UniverseArticleDocumentDataSlicesSlice = never;

/**
 * Content for Universe Article documents
 */
interface UniverseArticleDocumentData {
  /**
   * Title field in *Universe Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Placeholder title
   * - **API ID Path**: universeArticle.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Timestamp field in *Universe Article*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: Placeholder timestamp
   * - **API ID Path**: universeArticle.timestamp
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  timestamp: prismic.TimestampField;

  /**
   * Author field in *Universe Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Author name goes here
   * - **API ID Path**: universeArticle.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  author: prismic.RichTextField;

  /**
   * Description field in *Universe Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Placeholder description
   * - **API ID Path**: universeArticle.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Universe Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: universeArticle.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Article Content field in *Universe Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Article content goes here
   * - **API ID Path**: universeArticle.article_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  article_content: prismic.RichTextField;

  /**
   * Slice Zone field in *Universe Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: universeArticle.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<UniverseArticleDocumentDataSlicesSlice> /**
   * Meta Title field in *Universe Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: universeArticle.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Universe Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: universeArticle.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Universe Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: universeArticle.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Universe Article document from Prismic
 *
 * - **API ID**: `universeArticle`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type UniverseArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<UniverseArticleDocumentData>,
    "universeArticle",
    Lang
  >;

export type AllDocumentTypes =
  | ChapterDocument
  | DoodleDocument
  | HumanArticleDocument
  | LabsArticleDocument
  | PostDocument
  | UniverseArticleDocument;

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ChapterDocument,
      ChapterDocumentData,
      ChapterDocumentDataSlicesSlice,
      DoodleDocument,
      DoodleDocumentData,
      DoodleDocumentDataSlicesSlice,
      HumanArticleDocument,
      HumanArticleDocumentData,
      HumanArticleDocumentDataSlicesSlice,
      LabsArticleDocument,
      LabsArticleDocumentData,
      LabsArticleDocumentDataSlicesSlice,
      PostDocument,
      PostDocumentData,
      PostDocumentDataSlicesSlice,
      UniverseArticleDocument,
      UniverseArticleDocumentData,
      UniverseArticleDocumentDataSlicesSlice,
      AllDocumentTypes,
      TextBlockSlice,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
    };
  }
}
