# .github/workflows/vercel-preview.yml

name: Generate Vercel preview on dev branch (main)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # it needs write to create comment with preview url :)
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Vercel Preview
        id: vercel
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id:  ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          # no --prod, so preview

      # PLEASE TRY TO COMMENT ONLY IF IT'S A PR
      - name: Comment Preview URL on PR
        if: ${{ github.event_name == 'pull_request' && steps.vercel.outputs.preview-url }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `Preview URL: ${steps.vercel.outputs.preview-url}`,
            })