# .github/workflows/vercel-preview.yml

name: Generate Vercel preview on dev branch (main)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Vercel Preview
        id: vercel_preview
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token:   ${{ secrets.VERCEL_TOKEN }}
          github-token:   ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id:  ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          
      - name: Print preview URL
        if: github.event_name == 'push'
        run: echo "Preview URL -> ${{ steps.vercel_preview.outputs.preview-url }}"